---
output:  pdf_document
fontsize: 11pt
header-includes:
 - \usepackage{amsmath,amssymb,setspace}
 - \newcommand{\E}{\textrm{E}}
 - \newcommand{\var}{\textrm{var}}
 - \newcommand{\cov}{\textrm{cov}}
---

# Homework 1 Solutions


**Question 1**

```{r}
load("fertilizer_2000.RData")


# part (a)
nrow(fertilizer_2000)

# part (b)
fertilizer_2000[21,]$country

# part (c)
mean_gdp <- mean(fertilizer_2000$avgdppc)
mean_gdp

# part (d)
above_avg_gdp <- subset(fertilizer_2000, avgdppc > mean_gdp)
mean(above_avg_gdp$prec)
```

**Question 2**

```{r}
# part (a)
fibonacci <- function(n) {
  # handle n=1 or 2
  if (n==1) return(0)
  if (n==2) return(1)
  
  fib <- c(0,1) # set first two values
  for (i in 3:n) {
    fib[i] <- fib[i-1] + fib[i-2]
  }
  fib[n]
}

# check that it works
fibonacci(5)
fibonacci(8)
fibonacci(16)

# part (b)
alt_seq <- function(a,b,n) {
  if (n==1) return(a)
  if (n==2) return(b)
  
  alt_fib <- c(a,b)
  for (i in 3:n) {
    alt_fib[i] <- alt_fib[i-1] + alt_fib[i-2]
  }
  alt_fib[n]
}

# check that it works
alt_seq(a=3,b=7,n=4)
alt_seq(a=5,b=9,n=16)
```

