---
title: "ECON 8070 Course Material"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Syllabus](syllabus.pdf)

<span style="color:red"><b>Midterm 1 date changed to September 27</b></span>

# Homeworks

[HW 1](hw1.html), due Thursday, Sep. 1, [[[solutions](hw1_sol.pdf)]], [[[Rmd file](https://github.com/bcallaway11/bcallaway11.github.io/blob/master/Courses/ECON_8070_Fall_2022/hw1_sol.Rmd)]]

* Data: [fertilizer_2000.RData](fertilizer_2000.RData) [[[description](fertilizer_description.txt)]]

[HW 2](hw2.html), due Thursday, Sep. 15, [[[solutions](hw2_sol.pdf)]], [[[Rmd file](https://github.com/bcallaway11/bcallaway11.github.io/blob/master/Courses/ECON_8070_Fall_2022/hw2_sol.Rmd)]]

[Additional Practice Questions for Midterm 1](additional_practice_1.html), [[[partial solutions](additional_practice_1_partial_solutions.pdf)]] <span style="color: red; font-weight: bold;">These do not need to be turned in</span>

[HW 3](hw3.html), due Thursday, Oct. 13, [[[solutions](hw3_sol.pdf)]]

[Additional Practice Questions for Midterm 2](additional_practice_2.html), [[[solutions](additional_practice_2_sol.pdf)]] <span style="color: red; font-weight: bold;">These do not need to be turned in</span>

[HW 4](hw4.html), due Thursday, Dec. 1

# Course Material

We will cover the following topics:

(<span style="color: red; font-weight: bold;">Note:</span> Some of the material will be updated/expanded as we move through the semester.  Some of the topics at the end of the semester are tentative.)

0. [Introduction to R](introduction_to_R.html)

1. [Probability Theory](01_probability.html)

    - Introduction
    - Random Variables
    - Parametric Distributions
    - Multivariate Distributions

2. [Statistics](02_statistics.html)

    - Sampling
    - Law of Large Numbers
    - Central Limit Theorem
    - Method of Moments Estimation
    - Inference
    
3. [Linear Regression](03_regression.html)

    - Introduction/Review of Linear Algebra
    - Conditional Expectation and Projection
    - The Algebra of Least Squares
    - Least Squares Regression
    - Asymptotic Theory for Least Squares

# Slides

- First Week: [Introduction to ECON 8070](introduction_slides.html)

