---
title: "ECON 4750 Course Material"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Syllabus](syllabus.pdf)

<span style="color:red"><b>Midterm 1 date changed to September 27</b></span>

- [Course Notes](https://bcallaway11.github.io/econ_4750_notes/)

# Homeworks

[HW 1](hw1.html), due Tuesday, Sept. 6, [[[solutions](hw1_sol.html)]], [[[Rmd file](https://github.com/bcallaway11/bcallaway11.github.io/blob/master/Courses/ECON_4750_Fall_2022/hw1_sol.Rmd)]]

[HW 2](hw2.html), due Thursday, Sept. 22, [[[solutions](hw2_sol.html)]], [[[Rmd file](https://github.com/bcallaway11/bcallaway11.github.io/blob/master/Courses/ECON_4750_Fall_2022/hw1_sol.Rmd)]]

[HW 3](hw3.html), due Tuesday, Oct. 18, [[[solutions](hw3_sol.html)]]

[HW 4](hw4.html), due Tuesday, Nov. 8, [[[solutions](hw4_sol.html)]]

[HW 5](hw5.html), due Thursday, Dec. 1

# Projects

[Project 1](project1.html), due Tuesday, Nov. 22, [[[My version of the project](project1_sol.html)]]

- [house_price_train.csv](house_price_train.csv) &nbsp; | &nbsp; [house_price_test.csv](house_price_test.csv) &nbsp; | &nbsp; [data_description.txt](data_description.txt)

[Project 2](project2.html), This project is optional.  If you turn it in, it must be submitted by 11:59pm on Sunday, Dec. 11 (see details below).  

- [jtrain_observational.dta](jtrain_observational.dta) &nbsp; | &nbsp; [jtrain_observational_description.txt](jtrain_observational_description.txt) &nbsp; | &nbsp; [jtrain_experimental.dta](jtrain_experimental.dta) &nbsp; | &nbsp; [jtrain_experimental_description.txt](jtrain_experimental_description.txt) 

    On the syllabus, the project counts for 10% of your grade.  If you turn it in, your final grade will be calculated as on the syllabus.  If you do not turn it in, your grade will be out of 90 possible points.  For example, if you scored 75 on the first midterm, 85 on the second midterm, score 95 on the final, you have a 90 homework average, scored an 80 on the first project, and 100 attendance/participation score, but do not turn in the project, then your grade for the semester will be:
    
    `(.15*75 + .15*85 + .2*95 + .2*90 + .1*80 + .1*100)/.9 = 87.8`
    
    If you additionally turn in this project and make a 99 on it, then your grade for the semester will be
    
    `.15*75 + .15*85 + .2*95 + .2*90 + .1*80 + .1*100 + .1*99 = 88.9`

# Additional Course Materials

- First Week Slides: [What is Econometrics?](l1.html)

- [firm_data.csv](firm_data.csv) | [firm_data.RData](firm_data.RData) | [firm_data.dta](firm_data.dta)

**Additional Materials for Midterm 1**

* [Study Guide](midterm1_study_guide.html)

* [Additional Practice Questions](midterm1_extra_questions.pdf), [[[solutions](midterm1_extra_questions_sol.pdf)]]

* Additional office hours: Friday 1:30-3:00 (Zoom only, please contact me by email if you would like to meet during this time), Monday 9:30-11:00 (in person, Amos B408).

**Additional Materials for Midterm 2**

* [Study Guide](midterm2_study_guide.html)

* [Additional Practice Questions](midterm2_extra_questions.html), [[[solutions](midterm2_extra_questions_sol.html)]]

* Additional office hours: Friday 1:00-2:00pm, Monday 9:30-10:30am (in person, Amos B408).

# Data

This list only includes data that needs to be downloaded from the course website.  Other data is listed in the Course Notes along with steps to access the data and a link to a description of the data.

- [acs](data/acs.RData) [[description](data/acs_description.txt)]

- [banks](data/banks.RData) [[description](data/banks_description.txt)]

- [Birthweight_Smoking](data/birthweight_smoking.dta) [[description](https://www.princeton.edu/~mwatson/Stock-Watson_3u/Students/EE_Datasets/Birthweight_Smoking_Description.pdf)]

- [diamond_train](data/diamond_train.RData) [[description](https://www.kaggle.com/shivam2503/diamonds/)]

- [diamond_test](data/diamond_test.RData) [[description](https://www.kaggle.com/shivam2503/diamonds/)]

- [fertilizer_2000](data/fertilizer_2000.RData) [[description](data/fertilizer_description.txt)]

- [fertilizer_panel](data/fertilizer_panel.RData) [[description](data/fertilizer_description.txt)]

- [house](data/house.RData) [[description](data/house_description.txt)]

- [intergenerational_mobility](data/intergenerational_mobility.RData) [[description](data/intergenerational_mobility_description.txt)]

- [Lead_Mortality](data/Lead_Mortality.RData) [[description](http://www.princeton.edu/~mwatson/Stock-Watson_3u/Students/EE_Datasets/Lead_Mortality_Description.pdf)]

- [mlda](data/mlda.RData) [[description](data/mlda_description.txt)]

- [mutual_funds](data/mutual_funds.RData) [[description](data/mutual_funds_description.txt)]

- [rand_hie](data/rand_hie.RData) [[description](data/rand_hie_description.txt)]

- [titanic_training](data/titanic_training.csv) [[description](https://www.kaggle.com/c/titanic/data)]

- [titanic_testing](data/titanic_testing.csv) [[description](https://www.kaggle.com/c/titanic/data)]

- [us_data](data/us_data.RData)

# Code Challenges

* [Sep. 20](code_challenge1.html)

* [Sep. 29](code_challenge2.html)