---
title: "ECON 8080 Course Material"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- [Syllabus](syllabus.pdf)

# Homeworks

* [HW 1](hw1.html), due Thursday, Jan. 20 [[[solutions](hw1_sol.pdf)]]

  - Data: [fertilizer_2000.RData](fertilizer_2000.RData) [[[description](fertilizer_description.txt)]]
  
  - If you are interested, here is my [Rmarkdown file](https://github.com/bcallaway11/bcallaway11.github.io/blob/master/Courses/ECON_8080_Spring_2022/hw1_sol.Rmd) for generating the homework solutions.

* [HW 2](hw2.html), due Thursday, Feb. 3 [[[solutions](hw2_sol.pdf)]], [[[Rmarkdown file](https://github.com/bcallaway11/bcallaway11.github.io/blob/master/Courses/ECON_8080_Spring_2022/hw2_sol.Rmd)]]

* [Additional Problems for Midterm 1](additional_practice1.html), [[[solutions](additional_practice1_sol.pdf)]] <span style="color: red; font-weight: bold;">you do not need to turn these in</span>

# Course Material

We will cover the following topics:

(<span style="color: red; font-weight: bold;">Note:</span> Some of the material will be updated/expanded as we move through the semester.  Some of the topics at the end of the semester are tentative.)

0. [R Review/Introduction](introduction_to_R.html)

1. [Linear Regression](01_linear_regression.html)

2. [Hypothesis Testing]

3. [Resampling Methods]

4. [Alternative Approaches to Causal Inference]

5. [Introduction to Nonlinear Models]

6. [Panel Data Models]

7. [Causal Inference with Panel Data]

8. If we have time, an introduction to [Quantile Regression]

9. If we have time, an introduction to [Nonparametric Regression]

# Slides

- First Week: [Introduction to ECON 8080](introduction_slides.html)

