---
title: "Faster did Code"
output:
  md_document:
    variant: "markdown_github"
    preserve_yaml: TRUE
author: "brant"
date: '2021-12-10'
layout: single
permalink: /posts/did-improvements
categories:
  - Econometrics
  - Panel Data
  - did package
comments: true
---


```{r echo=FALSE}
base.dir <- "~/Dropbox/website/"
base.url <- "/"
fig.path <- "files/figures/"
# set knitr parameters
knitr::opts_knit$set(base.dir = base.dir, base.url = base.url)
knitr::opts_chunk$set(fig.path = fig.path) 
```

We just put out a big update to the `did` package (version 2.1).  It is on GitHub and should be on CRAN in a day or two.  This version contains a lot of behind-the-scenes improvement such as better error handling and substantially more thorough testing.  It also allows users to [use a universal base period in event studies](posts/event-study-universal-v-varying-base-period).

This post though is about speed improvements in the new version of the `did` package.  These are almost all coming from improved performance of our bootstrap procedure.  As a side-comment: we have always used the multiplier bootstrap, which is much, much faster than the empirical bootstrap to begin with, but we implemented the new version in C++ which results in notable improvements in computation time.  Using the multiplier bootstrap is what allows the `did` package to report, for example, uniform confidence bands for group-time average treatment effects and event studies; that is, they tend to be somewhat wider than pointwise confidence intervals but are robust to the multiple testing arising in both of these cases.


| Type | \# units | \# time periods | rows of data | old computation time | new computation time | percentage reduction | 
| :---: | :---: | :---:  | :---: | :---: | :---: | :---: |
| Balanced Panel | 5000 | 8 | 40,000 | 12.5 | 3.5 | 72% | 
| Unbalanced Panel | 5000 | 8 | 39,999 | 283.4 | 3.4 | 99% |
| Repeated Cross Sections | 5000 | 8 | 5000 | 9.3 | 3.4 | 63% |
| Larger Panel Data | 20,000 | 20 | 400,000 | 328.5 | 97.2 | 70% |

For the full code for this post, see: [https://github.com/bcallaway11/did/blob/master/tests/code_profiling.Rmd](https://github.com/bcallaway11/did/blob/master/tests/code_profiling.Rmd)